"""Content recommendation model."""
import uuid
from datetime import datetime
from app import db


class ContentRecommendation(db.Model):
    """Represents a content recommendation generated by Agent 3."""
    
    __tablename__ = "content_recommendations"
    
    id = db.Column(db.Integer, primary_key=True)
    uuid = db.Column(db.String(36), unique=True, nullable=False, default=lambda: str(uuid.uuid4()))
    profile_uuid = db.Column(db.String(36), db.ForeignKey("business_profiles.uuid"), nullable=False)
    query_uuid = db.Column(db.String(36), db.ForeignKey("discovered_queries.uuid"), nullable=False)
    content_type = db.Column(db.String(100), nullable=False)  # blog_post, landing_page, faq, guide, etc.
    title = db.Column(db.String(500), nullable=False)
    rationale = db.Column(db.Text, nullable=False)
    target_keywords = db.Column(db.JSON, nullable=False, default=list)  # List of keywords
    priority = db.Column(db.String(50), nullable=False, default="medium")  # high, medium, low
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    
    # Relationships
    profile = db.relationship("BusinessProfile", back_populates="recommendations")
    query = db.relationship("DiscoveredQuery", back_populates="recommendations")
    
    def to_dict(self):
        """Convert model to dictionary."""
        return {
            "recommendation_uuid": self.uuid,
            "target_query_uuid": self.query_uuid,
            "content_type": self.content_type,
            "title": self.title,
            "rationale": self.rationale,
            "target_keywords": self.target_keywords,
            "priority": self.priority,
            "created_at": self.created_at.isoformat() + "Z",
        }
